# Generated by Django 5.1.4 on 2024-12-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='question_text',
            new_name='category_text',
        ),
    ]
