# Generated by Django 5.1.4 on 2025-01-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinder', '0002_rename_question_text_category_category_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
